#!/bin/bash

# Time-machine-style backup

set -o nounset
set -o errexit

_HOME="$1"
_SRC_ROOT="$2"
_DEST_ROOT="$3"
_RSYNC_OPTS="$4"

_SCRIPT_NAME="${0##*/}"
_BACKUP_LOG="${_HOME}/${_SCRIPT_NAME}.log"

_set_date() {
  _DATE=`date "+%Y-%m-%dT%H:%M:%S"`
}

_run_backup() {
  _set_date
  echo "${_DATE} Started ${_SRC_ROOT} -> ${_DEST_ROOT}" >> "${_BACKUP_LOG}"

  local latest_dir="${_DEST_ROOT}/latest"
  local dest_dir="${_DEST_ROOT}/backup-${_DATE}"

  local cmd
  cmd="rsync -ax ${_RSYNC_OPTS} --link-dest=${latest_dir}"
  cmd+=" ${_SRC_ROOT} ${dest_dir} &>> ${_BACKUP_LOG}"

  eval $cmd

  # Replace the link to 
  rm -f "${latest_dir}"
  ln -s "${dest_dir}" "${latest_dir}"

  _set_date
  echo "${_DATE} Completed" >> "${_BACKUP_LOG}"
}

#-------------------------------------------------------------------------------

_run_backup

