#!/bin/bash

# Time-machine-style backup

set -o nounset

_HOME="$1"
_SRC_ROOT="$2"
_DEST_ROOT="$3"
_RSYNC_OPTS="$4"

_SCRIPT_NAME="${0##*/}"
_BACKUP_LOG="${_HOME}/${_SCRIPT_NAME}.log"

_set_date() {
  _DATE=`date "+%Y-%m-%dT%H:%M:%S"`
}

_run_backup() {
  _set_date
  echo "${_DATE} Started ${_SRC_ROOT} -> ${_DEST_ROOT}" | tee -a "${_BACKUP_LOG}"

  local latest_dir="${_DEST_ROOT}/latest"
  local dest_dir="${_DEST_ROOT}/backup-${_DATE}"
  mkdir -p "$dest_dir"

  local cmd
  if $_USE_SUDO ; then
    cmd+='sudo '
  fi
  cmd+="rsync -ax ${_RSYNC_OPTS} --link-dest=${latest_dir}"
  cmd+=" ${_SRC_ROOT} ${dest_dir} &>> ${_BACKUP_LOG}"

  echo "cmd=$cmd" >> ${_BACKUP_LOG}

  eval "$cmd"
  local err=$?

  # Replace the link to 
  rm -f "${latest_dir}"
  ln -s "${dest_dir}" "${latest_dir}"

  _set_date
  echo "${_DATE} Completed" | tee -a "${_BACKUP_LOG}"

  return $err
}

#-------------------------------------------------------------------------------

_run_backup

